In [122]:
import numpy as np
import pandas as pd
import collections

1. How likely is it that you roll doubles when rolling two dice?

In [10]:
outcomes = [1,2,3,4,5,6]

n_sim = 100_000

n_trials = 2

In [11]:
rolls = np.random.choice(outcomes,(n_sim,n_trials))
rolls

array([[5, 6],
       [5, 4],
       [1, 6],
       ...,
       [3, 2],
       [5, 1],
       [5, 2]])

In [127]:
dice_df = pd.DataFrame(rolls)
dice_df

0  1
0      5  6
1      5  4
2      1  6
3      4  1
4      2  4
...   .. ..
99995  1  4
99996  1  6
99997  3  2
99998  5  1
99999  5  2

[100000 rows x 2 columns]

In [135]:
dice_df.sort_index(axis=1)

0  1
0      5  6
1      5  4
2      1  6
3      4  1
4      2  4
...   .. ..
99995  1  4
99996  1  6
99997  3  2
99998  5  1
99999  5  2

[100000 rows x 2 columns]

In [136]:
dice_df['is_duplicate'] = np.where((dice_df[0]+dice_df[1])/2 ==dice_df[0], 'yes', 'no')

In [156]:
dupe_total = len(dice_df[dice_df.is_duplicate == 'yes'])

In [157]:
dupe_total / n_sim

0.16368

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [9]:
c_outcomes = ['H','T']

c_sim = 10_000

c_trials = 8

In [13]:
flips = np.random.choice(c_outcomes,(c_sim,c_trials))
flips

array([['T', 'T', 'T', ..., 'T', 'H', 'H'],
       ['H', 'H', 'H', ..., 'H', 'H', 'H'],
       ['T', 'H', 'T', ..., 'H', 'H', 'T'],
       ...,
       ['H', 'H', 'H', ..., 'H', 'H', 'T'],
       ['T', 'T', 'T', ..., 'H', 'T', 'T'],
       ['T', 'H', 'T', ..., 'T', 'H', 'T']], dtype='<U1')

In [15]:
head_count =(flips == 'H').sum(axis=1)
head_count

array([3, 6, 5, ..., 5, 2, 4])

In [16]:
heads3 = (head_count == 3).mean()
heads3

0.2121

In [18]:
more_than_three = (head_count > 3).mean()
more_than_three

0.6418

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [19]:
codeup_outcome = ['W1','W2','W3','D1']

codeup_sim = 10_000

codeup_trials = 2

In [20]:
drive = np.random.choice(codeup_outcome,(codeup_sim,codeup_trials))
drive

array([['W3', 'W2'],
       ['W2', 'W2'],
       ['D1', 'W1'],
       ...,
       ['W3', 'W3'],
       ['D1', 'D1'],
       ['D1', 'D1']], dtype='<U2')

In [22]:
ds = (drive == 'D1').sum(axis=1)
ds

array([0, 0, 1, ..., 0, 2, 2])

In [24]:
ds_odds = (ds == 2).mean()
ds_odds

0.0615

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [29]:
days = 5

pt_count = 17

In [30]:
poptarts = np.random.normal(3,1.5,size=10_000)
poptarts

array([5.01572113, 4.12367034, 4.45429655, ..., 4.11839249, 2.9803887 ,
       5.21612659])

In [33]:
poptarts.mean()

3.0312053045031653

In [34]:
pt_odds = pt_count - (days * poptarts.mean())
pt_odds

1.8439734774841732

5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate   observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [35]:
m_height = np.random.normal(178, 8, size=10_000)
f_height = np.random.normal(170, 6, size=10_000)

In [36]:
tall_f = (f_height > m_height).sum()
tall_f

2110

In [38]:
f_odds = (f_height > m_height).mean()
f_odds

0.211

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

- How likely is it that 450 students all download anaconda without an issue?

In [39]:
conda_outcome = 1/250
conda_outcome

0.004

In [55]:
conda_sim = 450

installs = np.random.random((conda_sim, 1))
installs

array([[0.56560066],
       [0.71307702],
       [0.91312005],
       [0.92159958],
       [0.04126921],
       [0.26218667],
       [0.939476  ],
       [0.63807044],
       [0.12660543],
       [0.63625225],
       [0.28034592],
       [0.21316157],
       [0.55770296],
       [0.03057572],
       [0.91016727],
       [0.25107916],
       [0.19136683],
       [0.82944175],
       [0.60987893],
       [0.4878772 ],
       [0.13092708],
       [0.51637515],
       [0.35949288],
       [0.14072868],
       [0.8283121 ],
       [0.22281808],
       [0.75056687],
       [0.20066118],
       [0.50423366],
       [0.90000529],
       [0.05566179],
       [0.11858241],
       [0.26677198],
       [0.12475228],
       [0.76998606],
       [0.0941129 ],
       [0.48884904],
       [0.67501994],
       [0.72199356],
       [0.75150492],
       [0.30947996],
       [0.1111055 ],
       [0.80930685],
       [0.95071569],
       [0.32700561],
       [0.07315689],
       [0.30908182],
       [0.510

In [56]:
corrupt = (installs < conda_outcome)
corrupt

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [57]:
pd.Series(corrupt.sum(axis=1)).value_counts()

0    449
1      1
dtype: int64

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

- How likely is it that a food truck will show up sometime this week?

In [83]:
ft_outcome = .7

day_sim = 5

appearance = np.random.random((day_sim))
appearance

array([0.00089303, 0.46264147, 0.84817004, 0.32016962, 0.109153  ])

In [84]:
ft_odds = (appearance >= ft_outcome)
ft_odds

array([False, False,  True, False, False])

In [85]:
ft_odds.mean()

0.2

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [158]:
people = 23
room_sim = 10_000
days = 365

In [161]:
birthday_sim = np.random.choice(days,(room_sim,people))
birthday_sim

array([[ 95, 263, 292, ..., 336, 360,  89],
       [209, 286, 329, ..., 167,  90,  57],
       [302, 249, 317, ..., 301,  85, 154],
       ...,
       [184, 196, 333, ...,  70, 109, 358],
       [ 56, 269,  24, ..., 157, 309, 319],
       [154, 232, 340, ..., 197, 273, 228]])

In [178]:
birthday_df = pd.DataFrame(birthday_sim)
birthday_df

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      95  263  292  131  326  291  114  153  257  132  ...   11  185  213   
1     209  286  329   43  295   59  203    7  310  262  ...  341  270   58   
2     302  249  317   57  278  304   98  353  204  347  ...   30  113  225   
3     288  338  199  276   10  209   18  167   85   17  ...  326  165  185   
4     298  188  275  341   82   19  265   27   17  359  ...  122   85   86   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  193  325  322  302   83  130  187   96  346   77  ...  356  200  330   
9996  275   75  178   54   53  285  103  228  363  162  ...  101  115   20   
9997  184  196  333  268   74  232  146  228   74  256  ...  230  164  204   
9998   56  269   24  252  352  181  262   51  171   24  ...  230  270   51   
9999  154  232  340  312  220  282  344  290  337  298  ...  335  184  309   

       16   17   18   19   20   21   22  
0     197  200  215   31  336  360   89  
1      30  208  179  285  167   90   57  
2      42  144  335    7  301   85  154  
3      56  119  199   50   38  227   28  
4      75  158  211  211  181   72  347  
...   ...  ...  ...  ...  ...  ...  ...  
9995   59   38  356  167  241  193  158  
9996  206  162  281    8   72  207  247  
9997  256  113  337  290   70  109  358  
9998  130  167  175  296  157  309  319  
9999  339  290  313  146  197  273  228  

[10000 rows x 23 columns]

In [179]:
unique_bday = birthday_df.nunique(axis=1)
unique_bday

0       23
1       23
2       23
3       21
4       22
        ..
9995    21
9996    21
9997    21
9998    21
9999    22
Length: 10000, dtype: int64

In [180]:
birthday_df['birthday_matches'] = np.where((people-unique_bday) >= 1, 'yes', 'no')
birthday_df

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0      95  263  292  131  326  291  114  153  257  132  ...  185  213  197   
1     209  286  329   43  295   59  203    7  310  262  ...  270   58   30   
2     302  249  317   57  278  304   98  353  204  347  ...  113  225   42   
3     288  338  199  276   10  209   18  167   85   17  ...  165  185   56   
4     298  188  275  341   82   19  265   27   17  359  ...   85   86   75   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  193  325  322  302   83  130  187   96  346   77  ...  200  330   59   
9996  275   75  178   54   53  285  103  228  363  162  ...  115   20  206   
9997  184  196  333  268   74  232  146  228   74  256  ...  164  204  256   
9998   56  269   24  252  352  181  262   51  171   24  ...  270   51  130   
9999  154  232  340  312  220  282  344  290  337  298  ...  184  309  339   

       17   18   19   20   21   22  birthday_matches  
0     200  215   31  336  360   89                no  
1     208  179  285  167   90   57                no  
2     144  335    7  301   85  154                no  
3     119  199   50   38  227   28               yes  
4     158  211  211  181   72  347               yes  
...   ...  ...  ...  ...  ...  ...               ...  
9995   38  356  167  241  193  158               yes  
9996  162  281    8   72  207  247               yes  
9997  113  337  290   70  109  358               yes  
9998  167  175  296  157  309  319               yes  
9999  290  313  146  197  273  228               yes  

[10000 rows x 24 columns]

In [181]:
match_count = len(birthday_df[birthday_df.birthday_matches == 'yes'])
match_count

4995

In [182]:
match_odds =  match_count/room_sim
match_odds

0.4995