In [183]:
import numpy as np
import pandas as pd
import collections

1. How likely is it that you roll doubles when rolling two dice?

In [184]:
outcomes = [1,2,3,4,5,6]

n_sim = 100_000

n_trials = 2

In [185]:
rolls = np.random.choice(outcomes,(n_sim,n_trials))
rolls

array([[3, 3],
       [4, 3],
       [5, 5],
       ...,
       [5, 2],
       [5, 6],
       [3, 6]])

In [186]:
dice_df = pd.DataFrame(rolls)
dice_df

0  1
0      3  3
1      4  3
2      5  5
3      3  1
4      6  6
...   .. ..
99995  1  1
99996  5  5
99997  5  2
99998  5  6
99999  3  6

[100000 rows x 2 columns]

In [135]:
dice_df.sort_index(axis=1)

0  1
0      5  6
1      5  4
2      1  6
3      4  1
4      2  4
...   .. ..
99995  1  4
99996  1  6
99997  3  2
99998  5  1
99999  5  2

[100000 rows x 2 columns]

In [136]:
dice_df['is_duplicate'] = np.where((dice_df[0]+dice_df[1])/2 ==dice_df[0], 'yes', 'no')

In [156]:
dupe_total = len(dice_df[dice_df.is_duplicate == 'yes'])

In [157]:
dupe_total / n_sim

0.16368

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [9]:
c_outcomes = ['H','T']

c_sim = 10_000

c_trials = 8

In [13]:
flips = np.random.choice(c_outcomes,(c_sim,c_trials))
flips

array([['T', 'T', 'T', ..., 'T', 'H', 'H'],
       ['H', 'H', 'H', ..., 'H', 'H', 'H'],
       ['T', 'H', 'T', ..., 'H', 'H', 'T'],
       ...,
       ['H', 'H', 'H', ..., 'H', 'H', 'T'],
       ['T', 'T', 'T', ..., 'H', 'T', 'T'],
       ['T', 'H', 'T', ..., 'T', 'H', 'T']], dtype='<U1')

In [15]:
head_count =(flips == 'H').sum(axis=1)
head_count

array([3, 6, 5, ..., 5, 2, 4])

In [16]:
heads3 = (head_count == 3).mean()
heads3

0.2121

In [18]:
more_than_three = (head_count > 3).mean()
more_than_three

0.6418

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [19]:
codeup_outcome = ['W1','W2','W3','D1']

codeup_sim = 10_000

codeup_trials = 2

In [20]:
drive = np.random.choice(codeup_outcome,(codeup_sim,codeup_trials))
drive

array([['W3', 'W2'],
       ['W2', 'W2'],
       ['D1', 'W1'],
       ...,
       ['W3', 'W3'],
       ['D1', 'D1'],
       ['D1', 'D1']], dtype='<U2')

In [22]:
ds = (drive == 'D1').sum(axis=1)
ds

array([0, 0, 1, ..., 0, 2, 2])

In [24]:
ds_odds = (ds == 2).mean()
ds_odds

0.0615

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [194]:
days = 5

pt_count = 17

In [195]:
poptarts = np.random.normal(3,1.5,size=(10_000,days))
poptarts

array([[ 4.49621858,  4.3822461 ,  3.47996586,  1.73062287,  3.55971239],
       [ 3.19239708,  3.28826159,  4.63239452,  3.92040342,  1.86296926],
       [ 1.67898881,  0.72347917,  4.79885203,  1.34108026,  1.83691988],
       ...,
       [ 2.55640353,  4.39325903,  4.94951385,  2.15526068,  4.32754815],
       [ 4.96008651,  2.85400897,  2.7002954 ,  5.11688006,  6.02804372],
       [ 2.37524817,  4.5371777 ,  3.87357139,  2.39359435, -0.42948926]])

In [196]:
pop_per_week = poptarts.sum(axis=1)
pop_per_week

array([17.64876581, 16.89642586, 10.37932016, ..., 18.38198525,
       21.65931465, 12.75010235])

In [197]:
(pop_per_week < 17).mean()


0.7329

5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate   observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [35]:
m_height = np.random.normal(178, 8, size=10_000)
f_height = np.random.normal(170, 6, size=10_000)

In [36]:
tall_f = (f_height > m_height).sum()
tall_f

2110

In [38]:
f_odds = (f_height > m_height).mean()
f_odds

0.211

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

- How likely is it that 450 students all download anaconda without an issue?

In [202]:
# conda_outcome = 1/250
# conda_outcome
outcomes = ['S', 'F']
n_students = 150

In [203]:
# conda_sim = 450

# installs = np.random.random((conda_sim, 1))
# installs

downloads = np.random.choice(outcomes, size =(10_000, n_students),
                              p = [249/250, 1/250])
downloads

array([['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ...,
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S']], dtype='<U1')

In [204]:
# corrupt = (installs < conda_outcome)
# corrupt

((downloads == 'S').sum(axis=1) < n_students).mean()

0.4487

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

- How likely is it that a food truck will show up sometime this week?

In [214]:
ft_outcome = .7

day_sim = 7

appearance = np.random.random((10_000,day_sim))
appearance

array([[9.52106437e-01, 2.61273694e-01, 7.93105433e-01, ...,
        5.77184376e-01, 1.50450265e-02, 9.71482390e-01],
       [8.42995543e-01, 1.74319094e-05, 6.04520726e-01, ...,
        8.09799819e-02, 5.60366838e-01, 9.15406506e-01],
       [5.92780289e-01, 3.37738394e-02, 8.42023396e-01, ...,
        5.43726940e-01, 1.82889579e-02, 6.64356335e-01],
       ...,
       [6.86895839e-01, 6.95480472e-01, 6.83913299e-01, ...,
        1.94284683e-02, 4.78785238e-01, 5.10048069e-01],
       [7.19601748e-01, 6.63370715e-01, 2.94281698e-01, ...,
        7.15613840e-01, 6.64145140e-01, 6.13975495e-02],
       [2.25911861e-01, 9.16268185e-01, 2.97619482e-01, ...,
        8.38620771e-01, 5.83737087e-01, 4.85692997e-01]])

In [215]:
ft_odds = (appearance < ft_outcome)
ft_odds

array([[False,  True, False, ...,  True,  True, False],
       [False,  True,  True, ...,  True,  True, False],
       [ True,  True, False, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [False,  True,  True, ..., False,  True,  True],
       [ True, False,  True, ..., False,  True,  True]])

In [224]:
(ft_odds.sum(axis=1) > 0).mean()

0.9998

8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [217]:
people = 40
room_sim = 10_000
days = 365

In [218]:
birthday_sim = np.random.choice(days,(room_sim,people))
birthday_sim

array([[319,  89, 325, ...,   1,  81, 133],
       [175, 145, 107, ..., 104, 188, 342],
       [282, 245,  47, ..., 342, 323, 320],
       ...,
       [287, 249, 106, ...,  83, 108, 242],
       [106, 268, 188, ..., 240, 153, 234],
       [359, 132,   4, ..., 335, 286,  56]])

In [219]:
birthday_df = pd.DataFrame(birthday_sim)
birthday_df

0    1    2    3    4    5    6    7    8    9   ...   30   31   32  \
0     319   89  325  144   52   10  201  240  347  327  ...  230  267  220   
1     175  145  107   58  319  156   91   93  169  356  ...   14  349  291   
2     282  245   47  121  120  233  342  219   41  257  ...  229   73  363   
3      96  213   66  242  101  153  233  278  166  278  ...  331  175  202   
4     312    9  269  208  290  172  120  249  279    6  ...  144  175  184   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  359  287   95  268  273   26   21   38  353   22  ...  144  324  172   
9996  154   21  226  216  220  125  324  264  256  126  ...  197   18  178   
9997  287  249  106   50  150  227  322  163   87  339  ...    1  259   36   
9998  106  268  188  187  124   67   65  192  267  301  ...   72  310  339   
9999  359  132    4  158   48   46  116  212  224   36  ...  306  145  252   

       33   34   35   36   37   38   39  
0     333  168  236  329    1   81  133  
1     181  336  212  177  104  188  342  
2     233  325   74  253  342  323  320  
3     129  224   24  109  238   64  166  
4      67   57   71  233   94  275  101  
...   ...  ...  ...  ...  ...  ...  ...  
9995   66   16   92    0  266  297  293  
9996   46   50  209  330   99  289  228  
9997  284  177  187  127   83  108  242  
9998  330  320  259  170  240  153  234  
9999  110  297  122  197  335  286   56  

[10000 rows x 40 columns]

In [220]:
unique_bday = birthday_df.nunique(axis=1)
unique_bday

0       38
1       38
2       37
3       36
4       37
        ..
9995    40
9996    37
9997    38
9998    38
9999    38
Length: 10000, dtype: int64

In [221]:
birthday_df['birthday_matches'] = np.where((people-unique_bday) >= 1, 'yes', 'no')
birthday_df

0    1    2    3    4    5    6    7    8    9  ...   31   32   33  \
0     319   89  325  144   52   10  201  240  347  327  ...  267  220  333   
1     175  145  107   58  319  156   91   93  169  356  ...  349  291  181   
2     282  245   47  121  120  233  342  219   41  257  ...   73  363  233   
3      96  213   66  242  101  153  233  278  166  278  ...  175  202  129   
4     312    9  269  208  290  172  120  249  279    6  ...  175  184   67   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  359  287   95  268  273   26   21   38  353   22  ...  324  172   66   
9996  154   21  226  216  220  125  324  264  256  126  ...   18  178   46   
9997  287  249  106   50  150  227  322  163   87  339  ...  259   36  284   
9998  106  268  188  187  124   67   65  192  267  301  ...  310  339  330   
9999  359  132    4  158   48   46  116  212  224   36  ...  145  252  110   

       34   35   36   37   38   39  birthday_matches  
0     168  236  329    1   81  133               yes  
1     336  212  177  104  188  342               yes  
2     325   74  253  342  323  320               yes  
3     224   24  109  238   64  166               yes  
4      57   71  233   94  275  101               yes  
...   ...  ...  ...  ...  ...  ...               ...  
9995   16   92    0  266  297  293                no  
9996   50  209  330   99  289  228               yes  
9997  177  187  127   83  108  242               yes  
9998  320  259  170  240  153  234               yes  
9999  297  122  197  335  286   56               yes  

[10000 rows x 41 columns]

In [222]:
match_count = len(birthday_df[birthday_df.birthday_matches == 'yes'])
match_count

8926

In [223]:
match_odds =  match_count/room_sim
match_odds

0.8926